services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: backend-container
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: frontend-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html
